sudo: false

language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - node_modules

os:
  - linux

install:
  - npm install
  - npm run install

script:
  - ./node_modules/.bin/elm-ordeal tests/Main.elm